name: Build Android

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install Dependencies
      run: |
        npm install
        npm install -g expo-cli

    - name: Build and Test
      run: |
        expo build:android -t apk
        cd android && ./gradlew assembleRelease

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: app-artifact
        path: ./android/app/build/outputs/apk/release/app-release.apk

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: app-artifact
